/**
 * Pure builder for the AMS access-notification email.
 *
 * No I/O, no env reads — everything comes in via `AccessEmailInput` so this is
 * trivially unit-testable and language/brand-agnostic. The HTML mirrors the
 * approved dark-header mockup: dark decorative banner (hosted PNG art +
 * HTML logo row), serif typography, «НАЗНАЧЕННАЯ РОЛЬ» card with a per-role
 * badge icon, orange CTA. Inline styles are mandatory — Gmail/Outlook strip
 * <style> blocks and modern CSS. Header art / role badges are PNGs served
 * from the app's own domain (public/email/*, generated by
 * scripts/gen-email-assets.mjs); with images blocked the header degrades to a
 * dark band with the HTML logo row and the role card keeps its text.
 *
 * Two kinds:
 *   - 'role'     → access granted: role card + «Войти в систему».
 *   - 'employee' → HR record created (no role yet): softer copy + «Открыть AMS».
 */

export type AccessEmailKind = 'role' | 'employee'

export interface AccessEmailInput {
  kind: AccessEmailKind
  /** Recipient display name (already resolved; falls back to email local-part upstream). */
  name: string
  /** Human-readable role label (RU), required for kind='role', ignored otherwise. */
  roleLabel?: string
  /** Role id (super_admin | asset_admin | tech_admin | employee) — selects the badge icon. */
  role?: string
  /** Absolute app URL for the CTA button + fallback link + hosted assets. */
  appUrl: string
  /** Brand shown in the header + sender ("AMS"). */
  brand: string
}

export interface RenderedEmail {
  subject: string
  html: string
  text: string
}

const ACCENT = '#F97316'
const SERIF = "Georgia,'Times New Roman',serif"
const SANS = 'Arial,sans-serif'
const KNOWN_ROLES = new Set(['super_admin', 'asset_admin', 'tech_admin', 'employee'])

/** Minimal HTML escaping for interpolated user-controlled strings. */
export function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

export function renderAccessEmail(input: AccessEmailInput): RenderedEmail {
  const { kind, appUrl, brand } = input
  const name = escapeHtml(input.name.trim() || brand)
  const url = escapeHtml(appUrl)
  const base = escapeHtml(appUrl.replace(/\/+$/, ''))
  const brandSafe = escapeHtml(brand)
  const isRole = kind === 'role'

  const subject = isRole
    ? `Вам открыт доступ в ${brand}`
    : `Вас добавили в ${brand}`

  const lead = isRole
    ? `Для вас открыт доступ в систему учёта активов <b style="color:#1A202C;">${brandSafe}</b>.<br>Ниже — назначенная роль и способ входа.`
    : `Вас добавили в систему учёта активов <b style="color:#1A202C;">${brandSafe}</b> как сотрудника.`

  // «НАЗНАЧЕННАЯ РОЛЬ» card — cream panel, badge icon by role id + serif label
  const roleKey = input.role && KNOWN_ROLES.has(input.role) ? input.role : null
  const roleCard = isRole && input.roleLabel?.trim()
    ? `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:22px 0 2px;">
         <tr><td style="background:#FBF4EA;border:1px solid #F0DFC8;border-radius:10px;padding:16px 20px 17px;">
           <div style="font:700 11px/1 ${SANS};letter-spacing:.14em;color:#B45309;">НАЗНАЧЕННАЯ РОЛЬ</div>
           <table role="presentation" cellpadding="0" cellspacing="0" style="margin-top:11px;"><tr>
             ${roleKey ? `<td style="padding-right:12px;" valign="middle"><img src="${base}/email/role-${roleKey}.png" width="34" height="34" alt="" style="display:block;border-radius:9px;"></td>` : ''}
             <td valign="middle" style="font:700 21px/1.2 ${SERIF};color:#1A202C;">${escapeHtml(input.roleLabel.trim())}</td>
           </tr></table>
         </td></tr>
       </table>`
    : ''

  const tail = isRole
    ? `Войдите в систему с помощью вашего Google-аккаунта — отдельный пароль не требуется.`
    : `Как только администратор назначит вам доступ, вы сможете войти по кнопке ниже с помощью вашего Google-аккаунта.`

  const ctaLabel = isRole ? 'Войти в систему →' : `Открыть ${brandSafe} →`

  const html = `<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;background:#e9edf2;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#e9edf2;padding:24px 12px;">
    <tr><td align="center">
      <table role="presentation" width="514" cellpadding="0" cellspacing="0" style="width:514px;max-width:100%;background:#ffffff;border:1px solid #e2e8f0;border-radius:14px;overflow:hidden;">

        <!-- Dark decorative header: art strip (image) + logo row (HTML fallback-safe) -->
        <tr><td style="background:#12141C;" bgcolor="#12141C">
          <img src="${base}/email/header.png" width="514" alt="" style="display:block;width:100%;height:auto;border:0;">
          <table role="presentation" cellpadding="0" cellspacing="0" style="padding:2px 26px 18px;"><tr>
            <td style="padding-right:11px;" valign="middle">
              <table role="presentation" cellpadding="0" cellspacing="0"><tr>
                <td width="40" height="40" align="center" valign="middle" style="background:${ACCENT};border-radius:20px;font:800 13px/1 ${SANS};color:#ffffff;letter-spacing:.02em;">${brandSafe}</td>
              </tr></table>
            </td>
            <td valign="middle">
              <div style="font:700 17px/1.2 ${SANS};color:#ffffff;">${brandSafe}</div>
              <div style="font:600 9.5px/1 ${SANS};letter-spacing:.24em;color:#8B93A3;margin-top:5px;">ASSET&nbsp;MANAGEMENT&nbsp;SYSTEM</div>
            </td>
          </tr></table>
        </td></tr>

        <!-- Body -->
        <tr><td style="padding:34px 34px 6px;">
          <div style="font:400 25px/1.3 ${SERIF};color:#1A202C;">Здравствуйте, <b>${name}</b>.</div>
          <div style="font:400 15.5px/1.65 ${SANS};color:#475569;margin-top:14px;">${lead}</div>
          ${roleCard}
          <div style="font:400 15.5px/1.65 ${SANS};color:#475569;margin-top:20px;">${tail}</div>
        </td></tr>

        <!-- CTA button (bulletproof) -->
        <tr><td style="padding:24px 34px 8px;">
          <table role="presentation" cellpadding="0" cellspacing="0"><tr>
            <td style="background:${ACCENT};border-radius:9px;">
              <a href="${url}" style="display:inline-block;padding:14px 28px;font:700 15px/1 ${SANS};color:#ffffff;text-decoration:none;border-radius:9px;">${ctaLabel}</a>
            </td>
          </tr></table>
        </td></tr>

        <!-- fallback link -->
        <tr><td style="padding:12px 34px 30px;">
          <div style="font:400 12px/1.6 ${SANS};color:#94a3b8;">Если кнопка не работает, откройте ссылку напрямую:<br>
            <a href="${url}" style="color:${ACCENT};text-decoration:none;">${url}</a></div>
        </td></tr>

        <!-- Footer -->
        <tr><td style="padding:16px 34px;background:#F4F5F7;border-top:1px solid #eef2f6;">
          <div style="font:400 11.5px/1.6 ${SANS};color:#94a3b8;">Это автоматическое письмо от системы ${brandSafe}. Отвечать на него не нужно.</div>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body></html>`

  const text = [
    `Здравствуйте, ${input.name.trim() || brand}!`,
    '',
    isRole
      ? `Вам открыт доступ в систему ${brand}.`
      : `Вас добавили в систему ${brand} как сотрудника.`,
    ...(isRole && input.roleLabel?.trim() ? [`Назначенная роль: ${input.roleLabel.trim()}`] : []),
    '',
    `${tail.replace(/<[^>]+>/g, '')}`,
    appUrl,
    '',
    `Это автоматическое письмо от системы ${brand}.`,
  ].join('\n')

  return { subject, html, text }
}
