// Shared non-feature components (AppShell, Sidebar, TopBar, etc.)
export { TopbarSlotContext, useTopbarSlot } from './TopbarSlotContext'
export type { TopbarSlotApi } from './TopbarSlotContext'
export { Sidebar } from './Sidebar'
export type { SidebarProps } from './Sidebar'
export { Breadcrumbs } from './Breadcrumbs'
export type { BreadcrumbsProps } from './Breadcrumbs'
export { LanguageToggle } from './LanguageToggle'
export { ProfileMenu } from './ProfileMenu'
export { SearchPalette } from './SearchPalette'
export type { SearchPaletteProps, SearchResult } from './SearchPalette'
export { TopBar } from './TopBar'
export type { TopBarProps } from './TopBar'
export { AppShell } from './AppShell'
export type { AppShellProps } from './AppShell'
