import {
  LayoutDashboard,
  ScanLine,
  Package,
  Wifi,
  Briefcase,
  PackagePlus,
  Minus,
  ArrowRightLeft,
  Wrench,
  KeyRound,
  Users,
  Building,
  Network,
  Tags,
  CircleDot,
  ShieldCheck,
  Shield,
  Crown,
  History,
  Settings,
  FileText,
  UserCircle,
  UserPlus,
  Search,
  Globe,
  ChevronDown,
  ChevronRight,
  Check,
  LogOut,
  Menu,
  X,
  Inbox,
  TriangleAlert,
  RefreshCw,
  Laptop,
  Monitor,
  User,
  HelpCircle,
  Loader2,
  Clock,
  MailCheck,
  Pencil,
  Trash2,
  Plus,
  Lock,
  // Category icons + badge icons
  Armchair,
  Box,
  House,
  Landmark,
  Printer,
  Router,
  Server,
  Smartphone,
  Table2,
  Tablet,
  Tv,
  RotateCcw,
  ListFilter,
  FileSpreadsheet,
  FileUp,
  // Filter-bar / sort icons
  Layers,
  ArrowDownNarrowWide,
  ArrowUpNarrowWide,
  ArrowDownAZ,
  ArrowDownZA,
  Hash,
  // Group-tab and empty-state icons
  MonitorSmartphone,
  SearchX,
  // Bulk-action icons
  UserCheck,
  // Asset-create form icons
  Calendar,
  ChevronLeft,
  ChevronsUpDown,
  MapPin,
  Warehouse,
  Building2,
  Cpu,
  CircleCheck,
  CopyPlus,
  FilePlus2,
  ArrowRight,
  CircleAlert,
  Save,
  GitBranch,
  LayoutList,
  Timer,
  UserRound,
  ArchiveX,
  CalendarDays,
  Send,
  Upload,
  FileX,
  Link,
  Unlink,
  Copy,
  // Tech-spec tile icons
  CircuitBoard,
  MemoryStick,
  HardDrive,
  Microchip,
  Fan,
  Plug,
  BatteryMedium,
  Bell,
  Mail,
  CalendarPlus,
  Link2,
  Phone,
  CheckCheck,
  ShoppingCart,
  ArrowLeft,
  AlertTriangle,
  Info,
  Square,
  ListChecks,
  OctagonX,
  PcCase,
  CircleX,
  ArrowLeftRight,
  ClipboardList,
  Gamepad2,
  type LucideIcon,
} from 'lucide-react'
import { cn } from '@/lib/utils'

const REGISTRY: Record<string, LucideIcon> = {
  'layout-dashboard': LayoutDashboard,
  package: Package,
  'package-plus': PackagePlus,
  minus: Minus,
  'arrow-right-left': ArrowRightLeft,
  wrench: Wrench,
  'key-round': KeyRound,
  users: Users,
  building: Building,
  network: Network,
  tags: Tags,
  'circle-dot': CircleDot,
  'shield-check': ShieldCheck,
  shield: Shield,
  crown: Crown,
  history: History,
  settings: Settings,
  'file-text': FileText,
  'user-circle': UserCircle,
  'user-plus': UserPlus,
  search: Search,
  globe: Globe,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  check: Check,
  'log-out': LogOut,
  menu: Menu,
  x: X,
  inbox: Inbox,
  'triangle-alert': TriangleAlert,
  'refresh-cw': RefreshCw,
  laptop: Laptop,
  monitor: Monitor,
  user: User,
  'loader-circle': Loader2,
  'loader-2': Loader2,
  clock: Clock,
  'mail-check': MailCheck,
  pencil: Pencil,
  'trash-2': Trash2,
  plus: Plus,
  lock: Lock,
  // Category icons + badge icons
  armchair: Armchair,
  box: Box,
  house: House,
  landmark: Landmark,
  printer: Printer,
  router: Router,
  server: Server,
  smartphone: Smartphone,
  'table-2': Table2,
  tablet: Tablet,
  tv: Tv,
  'rotate-ccw': RotateCcw,
  'list-filter': ListFilter,
  'file-spreadsheet': FileSpreadsheet,
  'file-up': FileUp,
  // Filter-bar / sort icons
  layers: Layers,
  'arrow-down-narrow-wide': ArrowDownNarrowWide,
  'arrow-up-narrow-wide': ArrowUpNarrowWide,
  'arrow-down-a-z': ArrowDownAZ,
  'arrow-down-z-a': ArrowDownZA,
  hash: Hash,
  // Group-tab and empty-state icons
  'monitor-smartphone': MonitorSmartphone,
  'search-x': SearchX,
  'user-check': UserCheck,
  // Asset-create form icons
  calendar: Calendar,
  'chevron-left': ChevronLeft,
  'chevrons-up-down': ChevronsUpDown,
  'map-pin': MapPin,
  warehouse: Warehouse,
  'building-2': Building2,
  cpu: Cpu,
  'circle-check': CircleCheck,
  'copy-plus': CopyPlus,
  'file-plus-2': FilePlus2,
  'arrow-right': ArrowRight,
  'alert-circle': CircleAlert,
  save: Save,
  'git-branch': GitBranch,
  'layout-list': LayoutList,
  timer: Timer,
  'user-round': UserRound,
  'archive-x': ArchiveX,
  'calendar-days': CalendarDays,
  send: Send,
  upload: Upload,
  'file-x': FileX,
  link: Link,
  unlink: Unlink,
  copy: Copy,
  // Tech-spec tile icons
  'circuit-board':  CircuitBoard,
  'memory-stick':   MemoryStick,
  'hard-drive':     HardDrive,
  microchip:        Microchip,
  fan:              Fan,
  plug:             Plug,
  'battery-medium': BatteryMedium,
  mail: Mail,
  'calendar-plus': CalendarPlus,
  'link-2': Link2,
  phone: Phone,
  'check-check': CheckCheck,
  'check-circle': CircleCheck,
  'shopping-cart': ShoppingCart,
  'arrow-left': ArrowLeft,
  'alert-triangle': AlertTriangle,
  info: Info,
  square: Square,
  'list-checks': ListChecks,
  bell: Bell,
  'octagon-x': OctagonX,
  'x-octagon': OctagonX,
  'pc-case': PcCase,
  'x-circle': CircleX,
  'arrow-left-right': ArrowLeftRight,
  'clipboard-list': ClipboardList,
  'gamepad-2': Gamepad2,
  'scan-line': ScanLine,
  wifi: Wifi,
  briefcase: Briefcase,
}

export interface IconProps {
  name: string
  size?: number
  className?: string
}

export function Icon({ name, size = 16, className }: IconProps) {
  const Cmp = REGISTRY[name] ?? HelpCircle
  if (!REGISTRY[name] && import.meta.env.DEV) {
    console.warn(`[Icon] unknown name "${name}" — rendering fallback`)
  }
  return (
    <Cmp
      size={size}
      strokeWidth={1.75}
      aria-hidden
      className={cn('inline-block shrink-0 align-[-2px]', className)}
    />
  )
}
